### ISSUE TITLE
The favicon no longer works in Umbraco, 7.5+

### ISSUE THREAD

**Issue by abjerner** [leekelleher/umbraco-environment-indicator#11]
This is probably more an Umbraco/ImageProcessor issue, so this is just to let you know ;)

With Umbraco 7.5, ImageProcessor added some extra security in regard to what is allowed in the query string of image URLs (this also applies outside of the `media` folder).

This means that calling an URL like `/umbraco/assets/img/application/logo_white.png?tint=1d991d` will now trigger a YSOD:

> The request /umbraco/assets/img/application/logo_white.png?tint=1d991d could not be understood by the server due to malformed syntax.

Closed issue on the Umbraco issue tracker: http://issues.umbraco.org/issue/U4-8976

**Comment by leekelleher** [comment]
@abjerner Thanks for letting me know... well that sucks! (for this package) 😿

**Comment by leekelleher** [comment]
Update, I've just gone through an upgrade to Umbraco v7.5.x and hit this issue.  The only resolution is to manually enable ImageProcessor's **tint** plugin.

I'm not sure whether to modify this package to support enabling ImageProcessor options, as it could open up other issues - which are far too much for this simple package to deal with.

I'll update the README with details of the resolution for v7.5+.
