### ISSUE TITLE
Umbraco v7.5+ ImageProcessor restrictions

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-environment-indicator#12]
Follow up from #11.

Update the README with details on how to enable ImageProcessor's **tint** plugin to support this package.

**Comment by leekelleher** [comment]
Closing, this is no longer an issue due to an alternative approach in PR #13

**Comment by highstone** [comment]
Psst, don't forget to update the NuGet package ;-)
I just noticed the issue after browsing the closed issues...
