### ISSUE TITLE
Update default colours - matching Umb 7.6

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-environment-indicator#15]
Update the default colours, matching new Umbraco 7.6 brand colour scheme.

We need colours for...

- [ ] Local environment
- [ ] Development environment
- [ ] Staging environment
- [ ] Live (Production) environment

Current colours (for v0.3.0) can be found here: [`cms-environment-indicator.js#L3-L6`](https://github.com/leekelleher/umbraco-environment-indicator/blob/0.3.0/src/App_Plugins/CmsEnvironmentIndicator/js/cms-environment-indicator.js#L3-L6)

**Comment by ed-parry** [comment]
Gave it a go, and updated the images for docs as well to give you a quick idea of the colour scheme. Happy to update if required, but think it works well. The red/orange are quite vibrant so hard to miss, and the other two are a little more subtle and less of a warning, with green obviously being the lowest risk environment.

**Comment by leekelleher** [comment]
Hey @ed-parry - thanks so much, legend!
I'll take a look at PR #16 tomorrow morning.

**Comment by leekelleher** [comment]
Closing this issue, I'll feedback on #16.
