### ISSUE TITLE
Check Database Environment Rather Than Hostname

### ISSUE THREAD

**Issue by Nicholas-Westby** [leekelleher/umbraco-environment-indicator#8]
You appear to just look at the hostname in the URL to ascertain which environment is currently displayed. However, I recommend storing this in the database, as the domain might be used for any environment.

This actually happened to me recently. Basically, one machine was hosting multiple sites, and one of the sites was taken offline. Because another site had a wildcard binding, the domain for the environment that got taken offline began pointing to the other environment, and there was no indication to the user that they were using the alternate environment.

If this stored the knowledge of which environment was which in the database, it would be more effective in guarding against a scenario like this.

**Comment by leekelleher** [comment]
Hi @Nicholas-Westby, thanks for the suggestion.

Yeah, currently the plugin is purely JS, so it only checks the the browser's domain/hostname.

I think it would be good to explore your suggestion some more. First question it raises for me is, how would the environment be initially set in the database?

**Comment by Nicholas-Westby** [comment]
You could set it to a randomly generated color if that environment has no color set yet. Then, you could provide a dashboard (or some mechanism) to allow the user to change the color on that environment.

**Comment by leekelleher** [comment]
I was thinking about your original question last night... I'm unsure about how your domain/environments are set-up. Could you provide any examples/details on the domain/environment structure?

**Comment by Nicholas-Westby** [comment]
So, I have Server1. Server1 has two websites setup in IIS, Website1 and Website2. Those each point to different folders on the file system. I have two domains, www.site.com and stage.site.com. Website1 has a wildcard binding matching any request sent to Server1's IP address. Website2 has a domain binding matching any request sent to stage.site.com. So, Website1 gets traffic for www.site.com and Website2 gets traffic for stage.site.com.

However, when I turned off Website2, traffic for stage.site.com started being directed to Website1. There was no indication of this to the CMS user.

**Comment by leekelleher** [comment]
Closing this issue off.  It's an interesting question, but I consider it currently out of scope for this package.
